- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetComponent.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetContract.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetFragment.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetModule.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetPresenter.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetTempActivity.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/res/layout/activity_time_sheet_temp.xml
- app/src/main/res/layout/fragment_time_sheet.xml
Redmine https://dev.framgia.com/redmine/issues/118420
Timesheet ui 2
> [Sprint 1] TimeSheet UI 2

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainModule.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/widget/UnSwipeViewPager.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/nav_header_main.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- https://dev.framgia.com/redmine/issues/118570
- Feature logic main screen
> [Sprint 1] Feature logic main screen

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/local/sharedprf/SharedPrefsKey.java
- app/src/main/java/com/framgia/wsm/data/source/local/sqlite/UserLocalDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/UserResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginModule.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginViewModel.java
Task: Login logic
Link redmine : https://dev.framgia.com/redmine/issues/118756
Effect: N/A
> [Sprint 1] Feature_login_logic

- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/wsm/screen/main/MainModule.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewPagerAdapter.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/utils/navigator/NavigateAnim.java
- app/src/main/res/drawable-xxhdpi/ic_menu_nav.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_container.xml
https://dev.framgia.com/redmine/issues/118570
Feature logic main screen 2
Effect : None
> [Sprint 1] Feature logic main screen 2

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/data/source/TimeSheetDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/TimeSheetRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/TimeSheetRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/screen/demo/DemoTimeSheetActivity.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetModule.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
redmine https://dev.framgia.com/redmine/issues/118420
Fix ui timesheet
> [Sprint 1] TimeSheet UI 3

- app/src/main/java/com/framgia/wsm/data/source/TimeSheetDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/TimeSheetRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/TimeSheetRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/TimeSheetResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetContract.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetModule.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetPresenter.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
Redmine https://dev.framgia.com/redmine/issues/119103
Fake data load time sheet
> [Sprint 1]feature load time sheet

- app/src/main/java/com/framgia/wsm/data/source/local/sharedprf/SharedPrefsKey.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginModule.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainModule.java
- app/src/main/java/com/framgia/wsm/screen/main/MainPresenter.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/drawable-xxhdpi/ic_logout.xml
- app/src/main/res/drawable/bg_side_nav_bar.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/nav_header_main.xml
- app/src/main/res/values/colors.xml
https://dev.framgia.com/redmine/issues/118570
Feature logic main screen final
Effect : None
> [Sprint 1] Feature logic main screen final

- app/build.gradle
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/drawable-xxhdpi/ic_menu_nav.xml
- app/src/main/res/drawable-xxhdpi/ic_notifications.xml
- app/src/main/res/drawable-xxhdpi/ic_placeholder_user.xml
- app/src/main/res/drawable/bg_side_nav_bar.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/nav_header_main.xml
- app/src/main/res/values/colors.xml
- https://dev.framgia.com/redmine/issues/118570
- Fix logic main screen
> [Sprint 1] Fix logic main screen

- app/src/androidTest/assets/features/main.feature
- app/src/androidTest/java/com/framgia/wsm/test/screen/login/MainPageTest.java
- app/src/main/res/drawable-xxhdpi/ic_menu_nav.xml
- https://dev.framgia.com/redmine/issues/118570
- Scenario test main screen
> [Sprint 1] Scenario test main screen

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/screen/main/MainComponent.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetFragment.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetModule.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/119103
Fake data load time sheet
> [Sprint 1] Feature load time sheet

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveComponent.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetModule.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/res/layout/activity_requestleave.xml
- app/src/main/res/layout/fragment_time_sheet.xml
> [Sprint 2] Feature request leave ui

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffComponent.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_request_off.xml
Task: Request off UI
Link redmine : https://dev.framgia.com/redmine/issues/119800
Effect: N/A
> [Sprint 2] Feature request off UI

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeComponent.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/layout/fragment_time_sheet.xml
Redmine https://dev.framgia.com/redmine/issues/119848
Create request overtime UI
> [Sprint 2] Create request overtime UI

- app/src/main/java/com/framgia/wsm/data/model/Branch.java
- app/src/main/java/com/framgia/wsm/data/model/Group.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- Feature create request leave ui #3
> [Sprint 2] Feature create request leave ui #3

- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- Fix AutoLayout
- Fix timesheet in February
- Fix show timesheet data when click next, preview
> [Fix] TimeSheetView

- app/src/main/AndroidManifest.xml
- app/src/main/res/drawable/border_button_create.xml
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- Feature create request leave ui #4
> [Sprint 2] Feature create request leave ui #4

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/drawable-xxhdpi/ic_arrow_drop_down.xml
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/strings.xml
- Feature create request leave ui #5
> [Sprint 2] Feature create request leave ui #5

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values/array.xml
- Feature create request leave ui #6
> [Sprint 2] Feature create request leave ui #6

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeComponent.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/119848
Create confirm overtime ui
> [Sprint 2] Request orverimte ui

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Task: Request off UI
Link redmine: https://dev.framgia.com/redmine/issues/119800
Effect: N/A
> [Sprint 2] Request off UI 2

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffComponent.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
Task: Request off UI
Redmine: https://dev.framgia.com/redmine/issues/119800
Effect: N/A
> [Sprint 2] Request off UI 3

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/screen/BaseRequestLeave.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/120137
- Feature confirm request leave ui #2
> [Sprint 2] Feature cofirm request leave ui #2

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_request_overtime.xml
https://dev.framgia.com/redmine/issues/120363
Request overtime logic
> [Sprint 2] Request overtime logic

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffComponent.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/res/drawable-xxhdpi/ic_date_created.xml
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values/strings.xml
Task: Confirm request off UI
Redmine: https://dev.framgia.com/redmine/issues/120555
Effect: N/A
> [Sprint 2] Confirm request off UI

- app/src/androidTest/assets/features/requestovertime.feature
Test UI request overtime
Field
- Project name: require
- Time start: require, không được trùng thời gian làm việc chính thức, bắt đầu từ 18h đối với ngày làm việc
- Reason: require
- Time end: tự động điền theo time start, thời gian phải sau time start
> Test UI request overtime

- app/src/androidTest/assets/features/requestoff.feature
Test UI request off
Project name:  not require
Position name:  not require
#Off have salary - Company pay
Type off: Điền ít nhất 1 type (Annual leave, Leave for marriage, Leave for child 's marriage, Funeral leave)
Time start: require, thời gian bắt đầu lớn hơn thời gian hiện tại
Time end: require, thời gian kết thúc lớn hơn thời gian bắt đầu,  Time end - Time start = Tổng day of Type Off
Reason: require
#Off have salary - Insurance coverage
Type off: Điền ít nhất 1 type (Leave for care of sick child, Pregnancy examination leave, Sick leave, Miscarriage leave, Maternity leave, Wife’s labor leave)
Time start: require, thời gian bắt đầu lớn hơn thời gian hiện tại
Time end: require, thời gian kết thúc lớn hơn thời gian bắt đầu,  Time end - Time start = Tổng day of Type Off
Reason: require …
> Test UI request off scenario

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/data/model/CompanyPay.java
- app/src/main/java/com/framgia/wsm/data/model/InsuranceCoverage.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/values/strings.xml
Task: Feature request off logic
Link redmine: https://dev.framgia.com/redmine/issues/120841
Task: N/A
> [Sprint 3]Feature request off logic

- app/src/androidTest/assets/features/requestleave.feature
- app/src/main/res/values-v21/styles.xml
- Scenario test request leave
- Link Mô tả : https://docs.google.com/spreadsheets/d/106xgL9S7_t0Wdqo66EuI2hGYSls5pXo1NN38tYxeRoM/edit#gid=0
> Scenario test request leave

- app/src/androidTest/assets/features/requestovertime.feature
> Fix test UI request overtime

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeaveActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeaveComponent.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeaveViewModel.java
- app/src/main/res/drawable-xxhdpi/ic_search.xml
- app/src/main/res/layout/activity_list_request_leave.xml
- app/src/main/res/layout/item_list_request_leave.xml
- app/src/main/res/values/strings.xml
Task: List request leave UI
Link redmine: https://dev.framgia.com/redmine/issues/121055
Effect: N/A
> [Sprint 3] Feature list request leave UI

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/screen/BaseRequestLeave.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values/array.xml
> Request leave logic

- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/OverTimeRequest.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/activity_request_overtime.xml
- https://dev.framgia.com/redmine/issues/120995
- Feature logic request overtime
> [Sprint 3] Feature logic request overtime

- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/listrequestleave/ListRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManager.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/layout/activity_list_request_leave.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
Task: List request leave UI
Link redmine: https://dev.framgia.com/redmine/issues/121055
Effect: N/A
> [Sprint 3]Feature list request leave UI 2

- app/src/main/java/com/framgia/wsm/screen/BaseRequestLeave.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values/array.xml
> Request leave logic 2

- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManager.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/120995
- Feature logic request overtime #2
1. Validate FromTime, ToTime when is picked
> [Sprint 3] Feature logic request overtime #2

- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManager.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
1. Dialog choose list signgle choose không cần click button bên dưới
2. Dialog list signgle choose truyền params là list string
3. Error Dialog
> Feature Update DialogManager

- app/src/main/java/com/framgia/wsm/data/model/Branch.java
- app/src/main/java/com/framgia/wsm/data/model/Group.java
- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/120995
- Feature logic request overtime #3 
1. Fix validate fields, model Request
2. Handler arrow back, title toolbar
> [Sprint 3] Feature logic request overtime #3

- app/src/main/java/com/framgia/wsm/data/model/LeaveType.java
- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/screen/BaseRequestLeave.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/res/layout/activity_request_leave.xml
Choose Branch,Group, fix leave type
> [Sprint 4] Request leave logic 3

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- https://dev.framgia.com/redmine/issues/121945
- Feature logic confirm request 
1. **Send request to server:** If success back to MainActivity, else show errorDialog and back to Activity Request Overtime
> [Sprint 4] Feature logic confirm request overttime

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestAdapter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestModule.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/RequestTypeAnim.java
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/item_list_request_off.xml
- app/src/main/res/layout/item_list_request_overtime.xml
Task: Feature list Off, OT, LE/IL UI
Link redmine: https://dev.framgia.com/redmine/issues/121055
Effect: N/A
> [Sprint 4]Fix list request 4

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimePresenter.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/layout_form_company_pay.xml
- app/src/main/res/layout/layout_form_insurance_coverage.xml
- Fix layout request Off
- Fix logic request overtime
> [Sprint 4] Fix layout request off

- app/src/main/java/com/framgia/wsm/screen/BaseRequestOff.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/122146
- Feature logic request off:
1. Tạo BaseRequestOff
2. Tất cả data đều xoay quanh 2 view là HaveSalary và NoSalary
> [Sprint 4] Feature logic request off

- app/src/main/java/com/framgia/wsm/data/model/CompanyPay.java
- app/src/main/java/com/framgia/wsm/data/model/InsuranceCoverage.java
- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/RequestOffRequest.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestAdapter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/wsm/utils/RequestType.java
- app/src/main/res/layout/item_list_request_leave.xml
- app/src/main/res/layout/item_list_request_off.xml
- app/src/main/res/layout/item_list_request_overtime.xml
Task: List request off logic
Redmine: https://dev.framgia.com/redmine/issues/122187
Effect: N/A
> [Sprint 4]List request off logic

- app/src/main/java/com/framgia/wsm/data/model/InsuranceCoverage.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/screen/BaseRequestOff.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/122146
- Feature request off logic #2
> [Sprint 4] Feature request off logic #2

- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/screen/BaseRequestLeave.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values/strings.xml
> [Sprint 3] Feature request leave logic 4

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
Task: List request off logic
Link redmine: https://dev.framgia.com/redmine/issues/122187
Effect: N/A
> [Sprint 4] List request off logic 2

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestModule.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/res/layout/item_list_request_off.xml
Task: List request off logic
Link redmine: https://dev.framgia.com/redmine/issues/122187
Effect: N/A
> [Sprint 4] List request off logic 3

- app/src/main/java/com/framgia/wsm/data/model/CompanyPay.java
- app/src/main/java/com/framgia/wsm/data/model/InsuranceCoverage.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/StringUtils.java
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/layout_form_company_pay.xml
- app/src/main/res/layout/layout_form_insurance_coverage.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/122146
- Feature request off logic #3
> [Sprint 4] Feature request off logic #3

- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/utils/StatusCode.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/item_list_request_off.xml
- app/src/main/res/values/strings.xml
Task: List request off logic
Link redmine: https://dev.framgia.com/redmine/issues/122187
Effect: N/A
> [Sprint 4] List request off logic 4 (Fake data)

- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/java/com/framgia/wsm/utils/validator/Validator.java
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/122146
- Feature request off logic #4
> [Sprint 4] Feature request off logic #4

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/item_list_request_leave.xml
- app/src/main/res/layout/item_list_request_off.xml
- app/src/main/res/layout/item_list_request_overtime.xml
Task: List request overtime + leave  logic
Link redmine: Over Time: https://dev.framgia.com/redmine/issues/122900
Late early: https://dev.framgia.com/redmine/issues/122899
Effect: N/A
> [Sprint 4] List request overtime + leave  logic

- app/src/main/res/drawable-xxhdpi/ic_position_name.xml
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/122999
- Fix ui confirm request off
> [Sprint 4] Fix ui confirm request off

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/StringUtils.java
- app/src/main/res/layout/layout_form_request_leave.xml
- app/src/main/res/values/strings.xml
> [Sprint 3] Feature request leave logic 5

- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/122999
- Feature confirm request off logic
> [Sprint 4] Feature confirm request off logic

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- https://dev.framgia.com/redmine/issues/122999
- Feature confirm request off logic #2
> [Sprint 5] Feature confirm request off logic #2

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
Redmine https://dev.framgia.com/redmine/issues/123357
Request server
> [Sprint 4] Feature confirm request leave logic 2

- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/res/layout/activity_request_overtime.xml
- Fix request overtime logic
- Effect : Activity Confirm request overtime
> Fix request overtime logic

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/utils/common/StringUtils.java
- app/src/main/res/layout/layout_form_company_pay.xml
- app/src/main/res/layout/layout_form_insurance_coverage.xml
- app/src/main/res/values/strings.xml
- Fix logic request off #2
1. Validate field have salary
> [Sprint 5] Fix logic request off #2

- app/src/main/java/com/framgia/wsm/data/model/Avatar.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/middleware/InterceptorImpl.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/BaseResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/UserProfileResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
Task: Implement login API
Link redmine: https://dev.framgia.com/redmine/issues/123537
Task: N/A
> [Sprint 4]Feature apply login API

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- Fix call back list request screen 
1. Call back list quest screen when creating form sucessfull
- Effect: None
> [Sprint 5] Fix call back list request screen

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/ActionType.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/123757
Feature request leave detail logic
> [Sprint 5] Feature request leave detail logic

- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/res/drawable-xxhdpi/ic_being_handled_by.xml
- app/src/main/res/drawable-xxhdpi/ic_status.xml
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/values-v21/styles.xml
- https://dev.framgia.com/redmine/issues/123824
- Feature request off detail logic
> [Sprint 5] Feature request off detail

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_time_sheet.xml
Redmine https://dev.framgia.com/redmine/issues/123857
Fixing float button menu
> Fix float button

- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/RequestOffResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- https://dev.framgia.com/redmine/issues/123826
- https://dev.framgia.com/redmine/issues/123825
- Feature request off edit && delete
> [Sprint 5] Feature request off edit && delete

- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestAdapter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/item_list_request_off.xml
- app/src/main/res/layout/item_list_request_overtime.xml
Task: Request OT detail
Link redmine : https://dev.framgia.com/redmine/issues/123798
Effevt: N/A
> [Sprint 5] Feature request OT detail 2

- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/item_list_request_off.xml
- app/src/main/res/layout/item_list_request_overtime.xml
Task: Request OT detail
Link redmine : https://dev.framgia.com/redmine/issues/123798
Effevt: N/A
> [Sprint 5] Feature request ot detail 3

- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManager.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/123826
- https://dev.framgia.com/redmine/issues/123825
- Feature request off edit delete #2
> [Sprint 5] Feature request off edit delete #2

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeModule.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
Task: Request OT edit delete
Link redmine : https://dev.framgia.com/redmine/issues/124199            
https://dev.framgia.com/redmine/issues/124200
Effect: N/A
> [Sprint 5] Feature request OT edit delete

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/ActionType.java
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/123898
Edit & delete request leave logic
> [sprint 5] feature edit & delete request leave

- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/values/strings.xml
> [Sprint 6] Fix request off edit

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
Redmine https://dev.framgia.com/redmine/issues/123898
Edit & delete request leave logic
> [Sprint 5] feature edit & delete request leave 2

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/res/layout/activity_confirm_request_off.xml
> [Sprint 6] Fix request off edit #2

- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/res/values/strings.xml
Task: Request OT edit delete
Link redmine : https://dev.framgia.com/redmine/issues/124199
https://dev.framgia.com/redmine/issues/124200
Effect: N/A
> [Sprint 5] Feature request ot edit delete 2

- app/src/main/java/com/framgia/wsm/data/model/OffType.java
- app/src/main/java/com/framgia/wsm/data/model/OffTypeDay.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/LeaveTypeResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/OffTypeResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- scripts/chatwork.rb
[Sprint Maintain] Feature get data leave type
Link redmine: https://dev.framgia.com/redmine/issues/124443
Task : Feature get data leave type
Effect: N/A
> Feature get data leave type

- app/src/main/java/com/framgia/wsm/data/source/TimeSheetRepository.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/layout/fragment_time_sheet.xml
Fix error current date, date title
> fix timesheet

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileActivity.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileComponent.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfilePresenter.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/res/layout/activity_update_profile.xml
- app/src/main/res/values/strings.xml
Task: Feature update profile UI
Link redmine : https://dev.framgia.com/redmine/issues/124444
Effect: N/A
> [Sprint 6] Feature update profile UI

- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarComponent.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarContract.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarFragment.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarModule.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarPresenter.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_holiday_calendar.xml
- app/src/main/res/values-sw360dp/dimens.xml
Redmine https://dev.framgia.com/redmine/issues/124473
Create holiday calendar UI
> [Sprint 6] Holiday calendar ui

- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values-v21/styles.xml
- https://dev.framgia.com/redmine/issues/124292
- Fix profile ui
> [Sprint 6] Fix profile ui

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/res/drawable-xxhdpi/ic_request_overtime.xml
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/item_list_request_overtime.xml
- app/src/main/res/values-sw360dp/dimens.xml
[Sprint 6] Filter Request OT Logic
Link : https://dev.framgia.com/redmine/issues/124446
Task : Filter Request OT Logic
Effect: N/A
> [Sprint 6] Filter Request OT Logic

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/res/drawable-xxhdpi/ic_remove.xml
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/item_list_request_leave.xml
[Sprint 6] Filter Request Leave Logic
Link redmine: https://dev.framgia.com/redmine/issues/124628
Effect: N/A
> [Sprint 6] Filter Request Leave Logic

- app/src/main/java/com/framgia/wsm/data/model/Avatar.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfilePresenter.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/layout/fragment_profile.xml
Task: Feature profile logic
Link redmine : https://dev.framgia.com/redmine/issues/124700
Effect: N/A
> [Sprint 6] Feature profile logic

- app/src/main/java/com/framgia/wsm/data/model/HolidayCalendar.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarAdapter.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarComponent.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarFragment.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarModule.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarViewModel.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/ItemHolidayCalendarViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_holiday_calendar.xml
- app/src/main/res/layout/item_holiday_calendar.xml
Redmine https://dev.framgia.com/redmine/issues/124473
Adapter, Data binding
> [Sprint 6] Holiday calendar UI 4

- app/src/main/java/com/framgia/wsm/screen/profile/ProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/screen/profile/branch/BranchAdapter.java
- app/src/main/java/com/framgia/wsm/screen/profile/branch/ItemBranchViewModel.java
- app/src/main/java/com/framgia/wsm/screen/profile/group/GroupAdapter.java
- app/src/main/java/com/framgia/wsm/screen/profile/group/ItemGroupViewModel.java
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/item_list_branch.xml
- app/src/main/res/layout/item_list_group.xml
Task: Feature profile logic
Link redmine : https://dev.framgia.com/redmine/issues/124700
Effect: N/A
> [Sprint 6] Feature profile logic 2

- app/src/main/java/com/framgia/wsm/data/source/HolidayCalendarDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/HolidayCalendarRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/HolidayCalendarRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/HolidayCalendarResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarContract.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarModule.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarPresenter.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarViewModel.java
- app/src/main/java/com/framgia/wsm/widget/holidaycalendar/HolidayCalendarView.java
Redmine https://dev.framgia.com/redmine/issues/124778
Request server, fake data
> [Sprint 6] Feature holiday calendar logic

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileActivity.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfilePresenter.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- app/src/main/res/layout/activity_update_profile.xml
- https://dev.framgia.com/redmine/issues/124684
- Feature update profile logic #2
1. Validate data, pick Image User
> [Sprint 6] Feature update profile logic #2

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/MainApplication.java
> Implement Fabric

- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationComponent.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationContract.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationDialogFragment.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationModule.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationPresenter.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_notification.xml
Redmine https://dev.framgia.com/redmine/issues/124925
Notification UI
> [Sprint 6] Notifiaction UI

- app/build.gradle
- app/google-services.json
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/FireBaseInstanceIDService.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- build.gradle
- dependencies.gradle
Task: Feature config FCM & handle receive notification
Link redmine : https://dev.framgia.com/redmine/issues/124972
Effect: N/A
> [Sprint 9] Feature config FCM & handle receive notification

- app/src/main/java/com/framgia/wsm/screen/notification/NotificationDialogFragment.java
- app/src/main/res/drawable-xxhdpi/ic_clear_all.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_notification.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/124925
Notification UI
> [Sprint 6] Notification UI 2

- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileActivity.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/RequestPermissionManager.java
- app/src/main/res/drawable-xxhdpi/ic_star.xml
- app/src/main/res/layout/activity_update_profile.xml
- https://dev.framgia.com/redmine/issues/124684
- Feature update profile logic #3
- Effect : None;
> [Sprint 6] Feature update profile logic #3

- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/UpdateProfileRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfilePresenter.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- https://dev.framgia.com/redmine/issues/124684
- Feature update profile logic #4
> [Sprint 6] Feature update profile logic #4

- app/src/main/res/drawable-xxhdpi/ic_change_password.xml
- app/src/main/res/drawable-xxhdpi/ic_edit.xml
- app/src/main/res/layout/fragment_profile.xml
Task: Feature  Profile UI
Link redmine : https://dev.framgia.com/redmine/issues/125235
Effect: N/A
> [Sprint 6] Feature fix profile UI

- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/RequestOffRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_confirm_request_off.xml
Task: Implement request off API
Link redmine : https://dev.framgia.com/redmine/issues/125244
Effect: N/A
> [Sprint 7] Implement request off API

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/StatusCode.java
Task: Implement request off API
Link redmine : https://dev.framgia.com/redmine/issues/125244
Effect: N/A
> [Sprint 7] Feature implement request off api 2

- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/activity_update_profile.xml
> [Sprint 7] Fix update profile ui #2

- app/src/main/java/com/framgia/wsm/data/model/RequestOff.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
Task: Implement request off API
Link redmine : https://dev.framgia.com/redmine/issues/125244
Effect: N/A
> [Sprint 7] Implement create request off api 3

- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/utils/common/StringUtils.java
- app/src/main/java/com/framgia/wsm/widget/CircleView.java
- app/src/main/res/drawable-xxhdpi/ic_user.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_update_profile.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values-v21/styles.xml
- Fix profile ui #2
1. Fix profule ui
2. Fix  menu navigation
> [Sprint 7] Fix profile ui #2

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordActivity.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordComponent.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/res/layout/activity_change_password.xml
- app/src/main/res/values/strings.xml
Task: Change password UI
Link redmine: https://dev.framgia.com/redmine/issues/125557
Effect: N/A
> [Sprint 8] Feature change password UI

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values/strings.xml
> [Sprint 7] Fix edit request overtime

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/res/layout/activity_update_profile.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/item_list_branch.xml
- app/src/main/res/layout/item_list_group.xml
Link redmine: https://dev.framgia.com/redmine/issues/125705
Effect: N/A
> [Sprint 7] Feature fix profile logic

- app/src/main/java/com/framgia/wsm/data/model/Setting.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfilePresenter.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileViewModel.java
- app/src/main/res/layout/fragment_setting_profile.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/strings.xml
[Sprint 7] Feature setting ui
Link : https://dev.framgia.com/redmine/issues/125558
Effect: N/A
> [Sprint 7] Feature setting ui 2

- app/src/main/java/com/framgia/wsm/data/model/Request.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/res/drawable/border_button_cancel.xml
- app/src/main/res/drawable/border_button_search.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/item_list_request_leave.xml
- app/src/main/res/layout/nav_header_main.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/126074
- Fix item request leave
> [Sprint 7] Fix item request leave

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/OverTimeRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestAdapter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/values/strings.xml
[Sprint 7] Rename request to LeaveRequest
Link : https://dev.framgia.com/redmine/issues/126068
Effect : N/A
> [Sprint 7] Rename request to LeaveRequest

- app/src/main/java/com/framgia/wsm/data/model/Notification.java
- app/src/main/java/com/framgia/wsm/screen/notification/ItemNotificationViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationAdapter.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationModule.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
- app/src/main/res/layout/fragment_notification.xml
- app/src/main/res/layout/item_notification.xml
Redmine https://dev.framgia.com/redmine/issues/124925
Notification UI
> [Sprint 6] Notification UI 3

- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/RequestOffRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/RequestOffResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestAdapter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffModule.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
[Sprint 7] Rename requestoff to offrequest
Link : https://dev.framgia.com/redmine/issues/126068
Effect: N/A
> [Sprint 7] Rename requestoff to offrequest

- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/utils/validator/ValidType.java
- app/src/main/java/com/framgia/wsm/utils/validator/Validator.java
- app/src/main/res/layout/activity_change_password.xml
- app/src/main/res/values/strings.xml
Link redmine: https://dev.framgia.com/redmine/issues/126086
Effect: N/A
> [Sprint 8] Feature change password logic

- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/ChangePasswordRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
Link redmine: https://dev.framgia.com/redmine/issues/126086
Effect: N/A
> [Sprint 8] Feature change password logic 2

- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/StringUtils.java
- https://dev.framgia.com/redmine/issues/126285
- Feature implement api request overtime
> [Sprint 7] Feature implement api request overtime

- app/src/main/java/com/framgia/wsm/data/model/ErrorMessage.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/ErrorResponse.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
> [Sprint 7] Fix error response

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/BaseRequestLeave.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
[Sprint 2] Implement api request leave
Link : https://dev.framgia.com/redmine/issues/126025
Effect: N/A
> [Sprint 2] Implement api request leave

- app/src/main/java/com/framgia/wsm/data/model/Company.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveModule.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/fragment_profile.xml
[Sprint 2] Implement api request leave
Link : https://dev.framgia.com/redmine/issues/126025
Effect: N/A
>  [Sprint 2] Implement api request leave 2

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/RequestLeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
[Sprint 2] Implement api request leave
Link : https://dev.framgia.com/redmine/issues/126025
Effect: N/A
> [Sprint 2] Implement api request leave 3

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/StatusCode.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/item_list_request_leave.xml
Link redmine: https://dev.framgia.com/redmine/issues/126504
Effect: N/A
> [Sprint 7] Feature implement get list request leave

- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/utils/binding/ColorManagers.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/values/strings.xml
redmine https://dev.framgia.com/redmine/issues/126520
Fix ui timehseet
> [Sprint 7] Fix UI Timesheet

- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- https://dev.framgia.com/redmine/issues/126521
- Feature implement api delete request overtime
1. Delete , update request overtime
> [Sprnt 7] Feature implement api delete request overtime

- app/src/main/java/com/framgia/wsm/data/model/Approver.java
- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/item_list_request_leave.xml
Link redmine: https://dev.framgia.com/redmine/issues/126550
Effect: N/A
> [Sprint 7] Feature get list request off

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/BaseRequestLeave.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_request_leave.xml
[Sprint 7] Implement api delete and edit request leave
Link : https://dev.framgia.com/redmine/issues/126580
Effect : N/A
> [Sprint 7] Implement api delete and edit request leave

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveActivity.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- Fix reload data after updater request
> [Sprint 7] Fix reload data after updater request

- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsComponent.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsModule.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/menu/menu_drawer.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/126810
- Feature_member_requests_ui
1. Add menu mange request
> [Sprint 8] Feature_member_requests_ui

- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/res/layout/activity_confirm_request_off.xml
Link redmine: https://dev.framgia.com/redmine/issues/126779
Effect: N/A
> [Sprint 7] Fix request off detail

- app/src/main/java/com/framgia/wsm/data/model/Notification.java
- app/src/main/java/com/framgia/wsm/data/source/NotificationDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/NotificationRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/NotificationRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/notification/ItemNotificationViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationContract.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationModule.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationPresenter.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
- app/src/main/res/layout/item_notification.xml
- app/src/main/res/values/colors.xml
redmine https://dev.framgia.com/redmine/issues/126811
Notification logic,fake data
> [Sprint 8] Feature notification logic

- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsModule.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/item_manage_list_request.xml
- app/src/main/res/menu/menu_drawer.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/126810
- Feature member request ui #2
1. Create adapter for three list request
> [Sprint 8] Feature member request ui #2

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
[Sprint 7] Fix Request Leave
Link : https://dev.framgia.com/redmine/issues/126923
Effect: N/A
> [Sprint 7] Fix Request Leave

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
redmine https://dev.framgia.com/redmine/issues/127042
Fix timesheet logic
> [Sprint 8] Fix timesheet logic

- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/StatusCode.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/item_list_request_off.xml
- app/src/main/res/layout/item_list_request_overtime.xml
- app/src/main/res/values/strings.xml
Link redmine: https://dev.framgia.com/redmine/issues/127060
Effect: N/A
> [Sprint 8] Feature delete request off

- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_confirm_request_off.xml
Link redmine: https://dev.framgia.com/redmine/issues/127141
Effect: N/A
> [Sprint 8] Feature fix edit request off logic

- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewPagerAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ActionRequestListener.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/item_manage_list_request.xml
- https://dev.framgia.com/redmine/issues/126810
- feature_member_request_ui_#3
1. Item list request UI
> [Sprint 8] Feature member request ui #3

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
[Sprint 7] Fix Request Leave
Link  : https://dev.framgia.com/redmine/issues/126923
Effect : N/A
>  [Sprint 7] Fix Confirm Request Leave

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsModule.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/item_manage_list_request.xml
- https://dev.framgia.com/redmine/issues/127233
- Feature members requests logic
1. Get three list request manage
> [Sprint 8] Feature members requests logic

- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
Task: Feature implement create request off api 2
Link redmine: https://dev.framgia.com/redmine/issues/127141
Effect: N/A
> [Sprint 8] Feature implement create request off api 2

- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
> [Sprint 8] Fix request overtime logic

- app/src/main/res/values-vi/array.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/127315Implement vietname language
> [Sprint 8] Implement vietname language

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ActionRequestListener.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- https://dev.framgia.com/redmine/issues/127233
- Feature members request logic #2
> [Sprint 8] Feature members request logic #2

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
Task: Feature implement create request off api 2
Link redmine: https://dev.framgia.com/redmine/issues/127141
Effect: N/A
> [Sprint 8] Feature fix create request off logic

- app/src/main/java/com/framgia/wsm/data/model/OffType.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailModule.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/fragment_member_request_detail.xml
[Sprint 8] Member request detail logic
Link : https://dev.framgia.com/redmine/issues/127332
Effect: N/A
> [Sprint 8] Member request detail logic

- app/src/main/res/drawable-xxhdpi/circle_company_holiday.xml
- app/src/main/res/drawable-xxhdpi/circle_weekend_holiday.xml
- app/src/main/res/drawable-xxhdpi/ic_info.xml
- app/src/main/res/layout/fragment_holiday_calendar.xml
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/values-vi/strings.xml
Redmine https://dev.framgia.com/redmine/issues/127338
Fix holiday calendar
> [Sprint 8] fix holiday calendar ui

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/res/drawable-xxhdpi/border_status_accept.xml
- app/src/main/res/drawable-xxhdpi/border_status_forward.xml
- app/src/main/res/drawable-xxhdpi/border_status_pending.xml
- app/src/main/res/drawable-xxhdpi/border_status_reject.xml
- app/src/main/res/layout/item_manage_list_request.xml
- app/src/main/res/values-v21/styles.xml
- Fix item list request manage
- Effect : none
> [Sprint 8] Fix item list request manage

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
[Sprint 7] Fix Request Leave
Link : https://dev.framgia.com/redmine/issues/126923
Effect : N/A
> [Sprint 7] Fix Request Leave #2

- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/layout_form_company_pay.xml
- app/src/main/res/layout/layout_form_insurance_coverage.xml
Task: Feature implement create request off api 3
Link redmine: https://dev.framgia.com/redmine/issues/127141
Effect: N/A
> [Sprint 8] Feature implement creat request off api 3

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
-  Fix reload data when visible hint
> [Sprint 8] Fix reload data when visible hint

- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/java/com/framgia/wsm/widget/holidaycalendar/HolidayCalendarView.java
- app/src/main/res/layout/fragment_setting_profile.xml
- app/src/main/res/layout/item_holiday_calendar.xml
Redmine https://dev.framgia.com/redmine/issues/127611
Fix UI Holiday calendar, Profile setting
> [Sprint 8] Fix UI Holiday calendar, Profile setting

- circle.yml
- scripts/chatwork.rb
- scripts/pushNotification.sh
- scripts/saddler.sh
Config CI Review & Push Notification
> Config CI Review & Push Notification

- app/src/main/java/com/framgia/wsm/data/model/QueryRequest.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- https://dev.framgia.com/redmine/issues/127631
- Feature implement api get list request ots manage
> [Sprint 8] Feature implement api get list request ots manage

- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/res/layout/activity_change_password.xml
Fix List Manager Request
Link redmine : https://dev.framgia.com/redmine/issues/127608
Effect: N/A
> [Sprint 8] Fix List Manager Request

- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_request_overtime.xml
> [Sprint 8] Fix logic request overtime

- app/src/main/java/com/framgia/wsm/data/model/QueryRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- Fix api get list request manage
> [Sprint 9] Fix api get list request manage

- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
Redmine https://dev.framgia.com/redmine/issues/127830
Fix timehseet logic
> [Sprint 9] Fix timesheet logic

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/res/layout/fragment_member_request_detail.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values/dimens.xml
[Sprint 8] Fix UI member request detail
Link : https://dev.framgia.com/redmine/issues/127832
Effect : N/A
> [Sprint 8] Fix UI member request detail

- app/src/main/res/drawable-xxhdpi/ic_clear_white.xml
- app/src/main/res/drawable-xxhdpi/ic_filter.xml
- app/src/main/res/drawable-xxhdpi/ic_search_white.xml
- app/src/main/res/drawable/border_textview_clear.xml
- app/src/main/res/drawable/border_textview_hide.xml
- app/src/main/res/drawable/border_textview_search.xml
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- [Sprint 9] Feature filter list request manage ui
> [Sprint 9] Feature filter list request manage ui

- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/layout_form_company_pay.xml
- app/src/main/res/layout/layout_form_insurance_coverage.xml
Task: Feature implement create request off api 3
Link redmine: https://dev.framgia.com/redmine/issues/127778
Effect: N/A
> [Sprint 8] Feature implement edit request off api

- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- Fix api get list request leaves manage
> [Sprint 9] Fix api get list request leaves manage

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/item_manage_list_request.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- Fix ui filter list request manage
> [Sprint 9] Fix ui filter list request manage

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- Feature scroll floating button behavior
> [Sprint 9] Feature scroll floating button behavior

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailDialogFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailModule.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/res/layout/fragment_member_request_detail.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
[Sprint 8] Get Data Member Request Detail
Link : https://dev.framgia.com/redmine/issues/128211
Effect : N/A
> [Sprint 8] Get Data Member Request Detail

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- Fake data when aprrove reject success
> [Sprint 9] Fake data when aprrove reject success

- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
Task: Feature implement editrequest off api 2
Link redmine: https://dev.framgia.com/redmine/issues/127778
Effect: N/A
> Feature implement edit request off api 2

- app/src/main/java/com/framgia/wsm/data/model/HolidayCalendar.java
- app/src/main/java/com/framgia/wsm/data/model/HolidayCalendarDate.java
- app/src/main/java/com/framgia/wsm/data/source/HolidayCalendarDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/HolidayCalendarRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/HolidayCalendarRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarPresenter.java
- app/src/main/java/com/framgia/wsm/widget/holidaycalendar/HolidayCalendarView.java
Redmine https://dev.framgia.com/redmine/issues/128259
Implement Api holiday calendar
> [Sprint 9] Implement Api holiday calendar

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/item_manage_list_request.xml
- app/src/main/res/values-vi/array.xml
- app/src/main/res/values/array.xml
- Fix filter list request manage with status
> [Sprint 9] Fix filter list request manage with status

- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/item_manage_list_request.xml
- app/src/main/res/values-v21/styles.xml
- Fix ui list request manage #2
> [Sprint 9] Fix ui list request manage #2

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/res/layout/fragment_member_request_detail.xml
[Sprint 8] Fix bug list request levave
Link : https://dev.framgia.com/redmine/issues/126504
Effect : N/A
> [Sprint 8] Fix bug list request levave

- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/layout/layout_form_company_pay.xml
- app/src/main/res/layout/layout_form_insurance_coverage.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Task: Feature fix request off logic
Link redmine: https://dev.framgia.com/redmine/issues/128487
Effect: N/A
> [Sprint 8] Feature fix request off logic

- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/ChangePasswordRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
Task: Feature fix request off logic
Link redmine: https://dev.framgia.com/redmine/issues/126086
Effect: N/A
> [Sprint 8] Feature implement change password api

- app/src/main/java/com/framgia/wsm/data/model/QueryRequest.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/layout/fragment_list_request.xml
- Fix get list request personal 
> [Sprint 9] Fix get list request personal

- app/src/main/res/layout/fragment_holiday_calendar.xml
Redmine 
Fix holiday calendar UI
> [Sprint 9] Fix holiday calendar UI

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/UpdateProfileRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileFragment.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfilePresenter.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/RetrofitUtils.java
- app/src/main/res/layout/fragment_profile.xml
> [Sprint 9] Fix update profile

- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- Fix logic filter request manage
> [Sprint 10] Fix logic filter request manage

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/ActionRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- Feature implement api aprrove reject request manage
> [Sprint 10] Feature implement api aprrove reject request manage

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
> [Sprint maintain] Fixbug timesheet

- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/SignInDataResponse.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/activity_main.xml
- Check user permission aprrove reject
- Effect : none
> [Sprint 10] Check user permission aprrove reject

- app/src/main/java/com/framgia/wsm/data/model/UserTimeSheet.java
Fix bug total dayoff timesheet
> [Sprint maintain] Fix timesheet logic

- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/layout_form_company_pay.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Task: [Sprint 8] Feature fix request off
Link redmine: https://dev.framgia.com/redmine/issues/129102
Effect: N/A
> [Sprint 8] Feature fix request off

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/ActionRequestResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- Refactor code approve, reject list request manage
> [Sprint 10] Refactor code approve, reject list request manage

- app/src/main/java/com/framgia/wsm/data/model/Notification.java
- app/src/main/java/com/framgia/wsm/data/source/NotificationDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/NotificationRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/NotificationRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/NotificationRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/NotificationResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/notification/ItemNotificationViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationContract.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationPresenter.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
Remine https://dev.framgia.com/redmine/issues/126811
Implement api notification
> [Sprint 10] Implement api notification

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileFragment.java
- Fix bug reload avatar drawer after update profile
> [Sprint 10] Fix bug reload avatar drawer after update profile

- app/src/main/java/com/framgia/wsm/data/model/ErrorMessage.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/ErrorResponse.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/res/layout/activity_change_password.xml
Task: [Sprint 8] Feature fix change password logic
Link redmine: https://dev.framgia.com/redmine/issues/129102
Effect: N/A
> [Sprint 8] Feature fix change password logic + request off

- app/src/main/res/layout/activity_update_profile.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values-v21/styles.xml
> [Sprint 10] Fix ui profile

- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/values/colors.xml
> [Sprint maintain] Fix time sheet ui

- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/SignInRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginContract.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
Task: [Sprint 9] Feature fix change password logic
Link redmine: https://dev.framgia.com/redmine/issues/129458
Effect: N/A
> [Sprint 9] Feature fix request off 3 + fix notification logic

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemRecyclerViewClickListener.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailDialogFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailModule.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
[Sprint 9] Implement api reject and approve member request 
Link : https://dev.framgia.com/redmine/issues/129532
Effect :N/A
> [Sprint 9] Implement api reject and approve member request 

- app/build.gradle
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/TypeToast.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
> [Sprint 10] Feature custom toast

- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainPresenter.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
Task: [Sprint 9] Feature fix request off + logout
Link redmine: https://dev.framgia.com/redmine/issues/129458
Effect: N/A
> [Sprint 9] Feature fix request off + logout

- app/src/main/res/drawable/border_button_blue.xml
- app/src/main/res/drawable/border_button_red.xml
Task: [Sprint Maintain] Fix Bug Main In Android 4.4 Next 
Link redmine: https://dev.framgia.com/redmine/issues/129471
Effect: N/A
> [Sprint Maintain] Fix Bug Main In Android 4.4 Next 

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/res/layout/fragment_member_request_detail.xml
[Sprint Maintain] Fix member request detail
Link : https://dev.framgia.com/redmine/issues/129697
Effect : N/A
> [Sprint Maintain] Fix member request detail

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
Task: [Sprint 9] Feature fix request off + logout
Link redmine: https://dev.framgia.com/redmine/issues/129813
Effect: N/A
> [Sprint 9]Feature fix create request overtime + leave

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
Task: [Sprint maintain] Fix datetimepicker on android API 19
Link redmine: https://dev.framgia.com/redmine/issues/129813
Effect: N/A
> [Sprint maintain] Fix datetimepicker on android API 19

- app/src/main/java/com/framgia/wsm/data/source/NotificationDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/NotificationRepository.java
- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/NotificationRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/NetworkModule.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/middleware/RxErrorHandlingCallAdapterFactory.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeavePresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffContract.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffPresenter.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationContract.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationDialogFragment.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeContract.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimePresenter.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- dependencies.gradle
- [Sprint 10] Convert project to rxjava 2
- Efect : None
> [Sprint 10] Convert project to rxjava 2

- app/src/main/res/layout/activity_change_password.xml
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/layout/activity_update_profile.xml
Task: [Sprint Maintain] Fix Bug Main In Api19
Link redmine: https://dev.framgia.com/redmine/issues/129471
Effect: N/A
> [Sprint Maintain]Fix Bug Main In Api19

- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- Fix main view model ( Check null fragment )
- Fix get list request manage with pending status
> [Sprint Maintain] Fix main view model && Fix get list request manage with pending status

- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainModule.java
- app/src/main/java/com/framgia/wsm/screen/main/MainPresenter.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationModule.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- app/src/main/res/layout/activity_main.xml
Remine https://dev.framgia.com/redmine/issues/126811
Implement api notification
> [Sprint 10] Implement notification api

- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_holiday_calendar.xml
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/fragment_time_sheet.xml
> [Sprint 10] Fix close FloatingActionMenu

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/fragment_list_request.xml
- Feature add button create request 
> [Sprint Maintain] Feature add button create request

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/activity_update_profile.xml
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/fragment_time_sheet.xml
- Fix approve reject list request manage
> [Sprint Maintain] Fix approve reject list request manage

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/fragment_time_sheet.xml
Add SwipeFresh List Manager Leave Request
Link redmine: https://dev.framgia.com/redmine/issues/130524
> [Sprint Maintain] Add SwipeFresh List Manager Leave Request

- app/src/main/java/com/framgia/wsm/data/model/QueryRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/screen/EndlessRecyclerOnScrollListener.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/drawable-xxhdpi/ic_not_found_data.xml
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- Feature Load more list request manage
> [Sprint Maintain] Feature Load more list request manage

- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
[Sprint Maintain][List OverTime ] Time button can't change when select time
Link : https://dev.framgia.com/redmine/issues/130599
Effect: N/A
> [Sprint Maintain][List OverTime ] Time button can't change when select time

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
Redmine https://dev.framgia.com/redmine/issues/130775
Fix timesheet UI
> task #130775- Fix timesheet UI

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetContract.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetModule.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetPresenter.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
[Bug] Unpaid leave of absence annotation is displayed with Emp code I/P
Count data: Title of count data items display incorrectly
Count data: Total of paid leave of absence, Total of unpaid leave of absence still display with Emp code I/P
Link: https://dev.framgia.com/redmine/issues/130582
https://dev.framgia.com/redmine/issues/130641
https://dev.framgia.com/redmine/issues/130626
Effect: N/A
> [Bug]ref bug #130582 #130641 #130626 - fix role of user and change name title

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_list_request.xml
Add SwipeFresh List Leave Request
> [Sprint Maintain] Add SwipeFresh List Leave Request

- app/src/main/java/com/framgia/wsm/data/model/NotificationOrEmailSetting.java
- app/src/main/java/com/framgia/wsm/data/model/Setting.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/source/UserDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileViewModel.java
- app/src/main/res/layout/fragment_setting_profile.xml
[Sprint 11] Implement api setting
Link : https://dev.framgia.com/redmine/issues/130814
Effect : N/A
> [Sprint 11] Implement api setting #1

- app/src/main/java/com/framgia/wsm/screen/profile/group/ItemGroupViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/layout/fragment_member_request_detail.xml
- app/src/main/res/layout/item_list_group.xml
Tại màn hình tạo mới request cá nhân, trường Group, thông tin Group của user chỉ hiển thị 1 mình tên group hiện tại mà user đang trực thuộc.Trong trường hợp này, mong muốn hiển thị đầy đủ thông tin của cả Division/Section/Group.
link redmine https://dev.framgia.com/redmine/issues/130801
Effect: 
+ Screen confim OverTime, Request Leave, Request Off
+ Screen Profile
+ Screen member request detail
> [Bug] ref bug #130801 - Edit Group Name To Full Name Group

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/res/layout/fragment_member_request_detail.xml
- Hiện tại sau khi manager (không phải cấp cao nhất) approve request thì không hiển thị "Nhóm đang xử lý" trong phần Request information. 
Trong trường hợp này mong muốn sẽ hiển thị "Nhóm đang xử lý" là cấp cao hơn của cấp vừa xử lý request.
- Link : https://dev.framgia.com/redmine/issues/130612
- Effect: N/A
> ref bug#130612 - Fix Approve, reject manage detail

- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewPagerAdapter.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
Hiển thị màn hình list request tương ứng khi kích vào notification (Notification nhận từ server thông qua Firebase Cloud Messaging)
https://dev.framgia.com/redmine/issues/130796
Effect : None
> ref task #130796 - Handle notification

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/drawable/border_button_accept_all.xml
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/item_manage_list_request.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- Feature approve all request manager ui
> [Sprint maintain] Feature approve all request manager ui

- app/src/main/java/com/framgia/wsm/data/model/Notification.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationDialogFragment.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
Redmine https://dev.framgia.com/redmine/issues/126811
Fix Handle notification click
> ref task #126811 Notification logic

- app/src/main/java/com/framgia/wsm/data/model/LeaveRequest.java
- app/src/main/java/com/framgia/wsm/data/model/OffRequest.java
- app/src/main/java/com/framgia/wsm/data/model/RequestOverTime.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/ActionRequest.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ActionRequestListener.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/item_manage_list_request.xml
- Feature approve all request manage logic
> [Sprint maintain] Feature approve all request manage logic

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/activity_request_overtime.xml
Sửa lỗi edit group ở các màn edit request https://dev.framgia.com/redmine/issues/130917
Clear datetime ở các màn quản lý member's request https://dev.framgia.com/redmine/issues/130999
Effect : None
> ref bug #130917 Can edit group, #130999 Clear datetime

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/ActionRequestResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- Feature approve all request manage logic #2
> [Sprint maintain] Feature approve all request manage logic #2

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetContract.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetFragment.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/130853
fixcan not display overtime in timesheet
> ref bug #130853 can not display overtime in timesheet

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
Fix status forward can't show when approve or reject member
Link : https://dev.framgia.com/redmine/issues/130612
Effect : N/A
> ref bug#130612 fix status forward and check null when approve or reject callback

- app/build.gradle
- app/src/main/java/com/framgia/wsm/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsComponent.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsContract.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsFragment.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsModule.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/utils/string/StringUtils.java
- app/src/main/res/layout/fragment_statistics.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-sw360dp/auto_dimens.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- dependencies.gradle
Feature Create UI Statistic Of Personal
Effect: N/A
> [Sprint Maintain]Feature Create UI Statistic Of Personal

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/131203
- Fix approve all request manage ui 
> [Sprint maintain] Fix approve all request manage ui

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
Redmine https://dev.framgia.com/redmine/issues/131186
fix orange color with user in white list
> ref bug #131186 fix orange color with user in white list

- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- Fix create form request overtime
https://dev.framgia.com/redmine/issues/130915
> ref bug #130915 Fix create form request overtime

- app/src/main/java/com/framgia/wsm/data/source/remote/api/middleware/InterceptorImpl.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- Fix login error token ( Incorrect token to crash app )
> [Sprint maintain] Fix login error token

- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticContainerAdapter.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsFragment.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsModule.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_statistics.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Feature Create UI Statistic Of Personal
Effect: N/A
> [Sprint Maintain]Feature Create UI Statistic Of Personal Next

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/activity_forgot_password.xml
Feature Forgot Password
Link redmine : https://dev.framgia.com/redmine/issues/131200
Effect: None
> [Sprint Maintain] Feature Forgot Password

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- https://dev.framgia.com/redmine/issues/131280
- Fix create request off  ( Remove validate fromtime )
- Effect : Screen create request off
> ref bug #131280 Fix create request off

- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
Redmine https://dev.framgia.com/redmine/issues/131437
Fix  Timesheet crash when have DayOffAfternoon and textMorning is null
> ref bug #131437 Timesheet crash when have dayoffAfternoon

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
Link : https://dev.framgia.com/redmine/issues/131185
Effect : N/A
> ref  bug#131185 check user have contract date and clear date request off

- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/layout_form_request_leave.xml
- Fix three create form request ui
> [Sprint maintain] Fix three create form request ui

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordActivity.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordComponent.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordViewModel.java
- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordViewModel.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginActivity.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginViewModel.java
- app/src/main/res/layout/activity_create_new_password.xml
- app/src/main/res/layout/activity_login.xml
Create New Password When Forgot password
link redmine: https://dev.framgia.com/redmine/issues/131200
> [Sprint Maintain] Create New Password When Forgot password

- app/src/main/java/com/framgia/wsm/data/model/Chart.java
- app/src/main/java/com/framgia/wsm/data/model/StatisticOfPersonal.java
- app/src/main/java/com/framgia/wsm/data/source/StatisticsDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/StatisticsRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/StatisticsRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/StatisticsResponse.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
Feature Logic Statistic Of Personal
Effect: N/A
> [Sprint Maintain]Feature Logic Statistic Of Personal

- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticContainerAdapter.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsContract.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsFragment.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsModule.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbymonth/StatisticsByMonthFragment.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbyyear/StatisticsByYearFragment.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
Feature Logic Statistic Of Personal Chart
Effect: N/A
> [Sprint Maintain]Feature Logic Statistic Of Personal Chart

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
Redmine https://dev.framgia.com/redmine/issues/131983
Validate max allow time IL/LE/LO
> ref Support #131983 Validate max allow time IL/LE/LO

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- Fix approve all request manage #2
- Crash app when update all with no current status
> [Sprint maintain] Fix approve all request manage #2

- app/src/main/java/com/framgia/wsm/screen/statisticsbymonth/StatisticsByMonthContract.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbymonth/StatisticsByMonthFragment.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbymonth/StatisticsByMonthModule.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbymonth/StatisticsByMonthPresenter.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbymonth/StatisticsByMonthViewModel.java
- app/src/main/res/layout/fragment_statistics_by_month.xml
Feature Logic Statistic Of Personal In Month
Effect: N/A
> [Sprint Maintain]Feature Logic Statistic Of Personal In Month

- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- ref bug #132019 Time item request is null
- Effect : item list request personal
https://dev.framgia.com/redmine/issues/132019
> ref bug #132019 Time item request is null

- app/src/main/java/com/framgia/wsm/screen/statisticsbyyear/StatisticsByYearContract.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbyyear/StatisticsByYearFragment.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbyyear/StatisticsByYearModule.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbyyear/StatisticsByYearPresenter.java
- app/src/main/java/com/framgia/wsm/screen/statisticsbyyear/StatisticsByYearViewModel.java
- app/src/main/res/layout/fragment_statistics_by_year.xml
Feature Logic Statistic Of Personal In Year
Effect: N/A
> [Sprint Maintain]Feature Logic Statistic Of Personal In Year

- app/src/main/java/com/framgia/wsm/firebase/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
Fix lỗi cập nhật ngày nghỉ còn lại
https://dev.framgia.com/redmine/issues/131000
Fix lỗi hiển thị thông báo sai khi click submit lần 2
https://dev.framgia.com/redmine/issues/131143
> ref bug #131000 Remaining day off, #131143 Error message

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordActivity.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordViewModel.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginActivity.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/activity_create_new_password.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Feature Create New Password 
Link redmine: https://dev.framgia.com/redmine/issues/131200
> [Sprint Maintain] Feature Create New Password Continue

- app/src/main/java/com/framgia/wsm/data/source/RequestDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/RequestRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/ResetPasswordRequest.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordViewModel.java
Feature Send New Password To Sever
Link redmine :  https://dev.framgia.com/redmine/issues/131200
> [Sprint Maintain] Feature Send New Password To Sever

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/132021
fix User still can edit Leave type on edit request IL/LE/LO
> ref bug #132021 User still can edit Leave type on edit request IL/LE/LO

- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/ActionRequestResponse.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/res/layout/fragment_member_request_detail.xml
Link : https://dev.framgia.com/redmine/issues/130612
Effect: N/A
> ref bug#130612 add being handled by

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/activity_request_overtime.xml
Fix Error message displays incorrectly when inputting invalid request time in Request IL(A) Wonman only
link redmine: https://dev.framgia.com/redmine/issues/132172
Effect : Screen Create Leave Request (In late (A) Woman)
> [Bug] refbug #132172 Fix Error message displays incorrectly when inputting invalid request time in Request IL(A) Wonman only

- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_statistics.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-sw1024dp/auto_dimens.xml
- app/src/main/res/values-sw1080dp/auto_dimens.xml
- app/src/main/res/values-sw1280dp/auto_dimens.xml
- app/src/main/res/values-sw1440dp/auto_dimens.xml
- app/src/main/res/values-sw2560dp/auto_dimens.xml
- app/src/main/res/values-sw320dp/auto_dimens.xml
- app/src/main/res/values-sw360dp/auto_dimens.xml
- app/src/main/res/values-sw3840dp/auto_dimens.xml
- app/src/main/res/values-sw384dp/auto_dimens.xml
- app/src/main/res/values-sw411dp/auto_dimens.xml
- app/src/main/res/values-sw480dp/auto_dimens.xml
- app/src/main/res/values-sw540dp/auto_dimens.xml
- app/src/main/res/values-sw600dp/auto_dimens.xml
- app/src/main/res/values-sw720dp/auto_dimens.xml
- app/src/main/res/values-sw800dp/auto_dimens.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/auto_dimens.xml
Feature Logic Statistic Of Personal Final
Effect: N/A
> [Sprint Maintain] Feature Logic Statistic Of Personal Final

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
Link : https://dev.framgia.com/redmine/issues/132095
Effect: N/A
> ref bug#132095 fix compensation to time can not auto fill time in request leave early (M)

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
fix time request off member detail
Link : None
Effect: N/A
> fix time request off member detail

- app/src/main/java/com/framgia/wsm/data/source/StatisticsDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/StatisticsRepository.java
- app/src/main/java/com/framgia/wsm/data/source/remote/StatisticsRemoteDataSource.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/service/WSMApi.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticContainerAdapter.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsContract.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManager.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/layout/fragment_statistics.xml
- app/src/main/res/layout/fragment_statistics_by_month.xml
- app/src/main/res/layout/fragment_statistics_by_year.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
> [Sprint Maintain]Fix UI Statistic

- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsViewModel.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/layout/fragment_statistics.xml
Fix Logic Statistic
Effect: N/A
> [Sprint Maintain]Fix Logic Statistic

- app/src/main/java/com/framgia/wsm/data/source/remote/api/request/ResetPasswordRequest.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordContract.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordPresenter.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordViewModel.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginActivity.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
> [Sprint Maintain] Edit Reset Password

- app/src/main/java/com/framgia/wsm/data/model/LeaveType.java
- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/UserType.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
Redmine
- https://dev.framgia.com/redmine/issues/132116
- https://dev.framgia.com/redmine/issues/132020
- https://dev.framgia.com/redmine/issues/132090
Fix validate request leave for special user
> ref bug #132090 #132116 #132020 validate special user

- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/layout/fragment_time_sheet.xml
- https://dev.framgia.com/redmine/issues/132375
- Fix cut date off month
- Effect : Time sheet View
- Thiết lập lại ngày bắt đầu với ngày kết thúc cho phù hợp khi văn phòng thay đổi giờ làm việc
> [Sprint maintain] Fix cut date off month

- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
Redmine https://dev.framgia.com/redmine/issues/132242
Update Working Calendar For Compensation Day
> ref task #132242 Update Working Calendar For Compensation Day

- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarContract.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarFragment.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarViewModel.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileFragment.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileContract.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileFragment.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileViewModel.java
- Fix load data at first tme when visible hint
> [Sprint maintain] Fix load data at first tme when visible hint

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsModule.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsPresenter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- Fix current month date list request
> [Sprint maintain] Fix current month date list request

- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/utils/StatusCode.java
- app/src/main/java/com/framgia/wsm/utils/binding/ColorManagers.java
- app/src/main/res/drawable-xxhdpi/ic_status_cancel.xml
- app/src/main/res/layout/item_manage_list_request.xml
- app/src/main/res/values-vi/array.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- Feature add status canceled 
> [Sprint maintain] Feature add status canceled

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/activity_request_overtime.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Fix validate email message
https://dev.framgia.com/redmine/issues/132451
Fix edit group message
https://dev.framgia.com/redmine/issues/130917
> ref bug #132451 Error email message, #130917 Message edit Group

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/layout/fragment_member_request_detail.xml
>  update status cancel

- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- https://dev.framgia.com/redmine/issues/132375
- Fix calendar cut off date before 16
> [Sprint maintain] Fix calendar cut off date before 16

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
> ref bug fix status cancel

- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/layout/activity_login.xml
Fix clear time request lIL/LE/LO
https://dev.framgia.com/redmine/issues/132779
Fix password error message
https://dev.framgia.com/redmine/issues/132451
> ref bug #132779 Clear time, #132451 Error message

- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/res/layout/fragment_profile.xml
Link : https://dev.framgia.com/redmine/issues/133125
Effect : N/A
> ref bug#133125 hide Start probation date and End probation date.

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/res/layout/activity_update_profile.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/133371
- Fix load user when updated success ( Screen Profile )
- https://dev.framgia.com/redmine/issues/133366
- The birthday and contract date are displayed format dd/mm/yyyy instead of mm/dd/yyyy when users use English language ( Sreen edit profile)
> ref #bug_133371, #bug_133366 Fix load user when updated success

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
Link : https://dev.framgia.com/redmine/issues/132812
Effect : N/A
> ref bug#132812 fix Crash app when user click button "OK" of Compensation from

- app/src/main/AndroidManifest.xml
Add the path to open the app in feature Reset password
Link redmine: https://dev.framgia.com/redmine/issues/133448
> [Sprint Maintain] Add the path to open the app in feature Reset password

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
Remine https://dev.framgia.com/redmine/issues/132927
Error message displays when inputting time request
> ref bug #132927 Error message displays when inputting time request

- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/133369
-  Fix edit birthday user : Error message is displayed incorrectly when user submitting form with Birthday is under employment
> ref bug#133369 Fix edit birthday user

- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticContainerAdapter.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
> [Sprint Maintain]Fix UI In Statistic Screen

- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordActivity.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Edit Error Message When User Edit  Password with Current Password Incorrect
Link redmine: https://dev.framgia.com/redmine/issues/133123
Effects: N/A
> [Bug] Fix bug #133123 Edit Error Message When User Edit  Password with Current Password Incorrect

- app/src/main/res/drawable/button_animation.xml
- app/src/main/res/layout/activity_login.xml
Add Effects Click Button Login
> [Sprint Maintain] Add Effects Click Button Login

- app/src/main/java/com/framgia/wsm/firebase/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/screen/main/MainModule.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Update user profile when change Group, Branch
display message when click notification
https://dev.framgia.com/redmine/issues/133129
> ref bug #133129 Update profile

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileActivity.java
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- Fix format date list request manage 
- Effect : Screen list request manage
> [Sprint maintain] Fix format date list request manage

- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/res/layout/activity_update_profile.xml
Link: https://dev.framgia.com/redmine/issues/133125
Effect: N/A
>  ref bug#133125 hide probation date

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/133571
Compesation time auto-fill is incorect with user has baby
> ref bug 133571 Compesation time auto-fill is incorect with user has baby

- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordViewModel.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Edit Message Invalid Current Password And Fix Message Confirm Password Invalid
Link redmine: https://dev.framgia.com/redmine/issues/133123
> [Bug] #133123 Edit Message Invalid Current Password And Fix Message Confirm Password Invalid

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/utils/FileUtils.java
- https://dev.framgia.com/redmine/issues/133371
- Fix update avatar && remove validate request off with Sunday, Saturday
- Effect : Screen request off, Edit profile
> [Sprint maintain] Fix update avatar && remove validate request off with Sunday, Saturday

- app/src/main/java/com/framgia/wsm/firebase/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
display message when click notification
https://dev.framgia.com/redmine/issues/133129
> ref bug #133129 Message click notification

- app/src/main/java/com/framgia/wsm/data/source/remote/api/error/Type.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/BaseResponse.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailPresenter.java
- app/src/test/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailPresenterTest.java
> [Sprint maintain] Feature unit test screen member request detail

- app/src/main/java/com/framgia/wsm/data/source/UserRepository.java
- app/src/main/java/com/framgia/wsm/screen/changepassword/ChangePasswordPresenter.java
- app/src/test/java/com/framgia/wsm/screen/changepassword/ChangePasswordPresenterTest.java
Create Unit Test In Change Password Screen
> [Sprint Maintain]Create Unit Test In Change Password Screen

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/res/layout/activity_request_leave.xml
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/menu/menu_drawer.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Edit Navigate To Create Request Off And Create Request Other
Link redmine: https://dev.framgia.com/redmine/issues/133559
> [Bug] Fix bug #133559 Edit Navigate To Create Request Off And Create Request Other

- app/src/main/java/com/framgia/wsm/data/event/UpdateNumberNotificationEvent.java
- app/src/main/java/com/framgia/wsm/data/event/UpdateRemainingDayOff.java
- app/src/main/java/com/framgia/wsm/firebase/FireBaseMessageService.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
Update number notification when receive notification
Screen effect: Main Screen
Update Remaining dayoff
https://dev.framgia.com/redmine/issues/131000
> [Sprint Maintain] Update number notification, update remaining dayoff # #131000

- app/src/main/java/com/framgia/wsm/utils/FileUtils.java
- https://dev.framgia.com/redmine/issues/133371
- Fix update avatar #2 ( Tên ảnh bị trùng nên update không được)
- Effect : Edit profile
> [Sprint maintain] Fix update avatar #2

- circle.yml
> Fix CI - Update Ruby Version

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/FileUtils.java
- https://dev.framgia.com/redmine/issues/133371
- Random tên file ảnh bằng số sang chuỗi ngẫu nhiên
- https://dev.framgia.com/redmine/issues/133823
- Fix reload data when swipe
> ref bug#133823 Fix reload data when swipe

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_list_request.xml
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Edit Navigation when click notification with manager - Edit Text when not find request and can't load data
Link redmine: https://dev.framgia.com/redmine/issues/133559
Effect: Main, Manager Request, Personal Request
> Edit Navigation when click notification with manager - Edit Text when not find request and can't load data

- app/src/main/java/com/framgia/wsm/data/model/LeaveType.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/133802
Create request with time request less than 30 min
> ref bug #133802 request with time request less than 30 min

- app/src/main/java/com/framgia/wsm/data/model/StatisticOfPersonal.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/response/BaseResponse.java
- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsPresenter.java
- app/src/test/java/com/framgia/wsm/screen/statistics/StatisticsPresenterTest.java
Write Unit Test Statistic Of Personal Screen
> Write Unit Test Statistic Of Personal Screen

- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestAdapter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
Link : https://dev.framgia.com/redmine/issues/133805
Effect : N/A
> ref bug#133805 set time by branch

- app/src/main/AndroidManifest.xml
- Fix ui when show keyboard
- Effect : Header navagation, list request manager
> [Sprint maintain] Fix ui when show keyboard

- app/src/main/java/com/framgia/wsm/screen/confirmrequestleave/ConfirmRequestLeaveViewModel.java
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/133998
fix missing time of creation
> ref bug #133998 missing time of creation

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/test/java/com/framgia/wsm/screen/listrequest/ListRequestPresenterTest.java
> [Unit Test] feature unit test list request

- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordViewModel.java
Navigation When send Email Success
Link redmine: https://dev.framgia.com/redmine/issues/134045
> [Bug] Fix bug #134045 - Navigation When send Email Success

- app/src/main/res/values/array.xml
> Fix Status In List

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
Edit UI Manager Request
Link redmine: https://dev.framgia.com/redmine/issues/133482
> [Bug] Fix bug #133482 - Edit UI Manager Request

- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- Fix TimeSheetView by work around
> Fix TimeSheetView

- app/src/main/java/com/framgia/wsm/data/model/HolidayCalendarDate.java
- app/src/main/java/com/framgia/wsm/data/model/TimeSheetDate.java
- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarViewModel.java
- app/src/main/java/com/framgia/wsm/widget/holidaycalendar/HolidayCalendarView.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/layout/fragment_holiday_calendar.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/134024
Fix holiday duplicated with weekend day
> ref bug 134024 holiday duplicated with weekend day

- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordPresenter.java
- app/src/test/java/com/framgia/wsm/screen/forgotpassword/ForgotPasswordPresenterTest.java
> [Unit Test] Unit Test forgot password

- app/google-services.json
Feature update google services
> Feature update google services

- app/src/main/java/com/framgia/wsm/screen/login/LoginContract.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginModule.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/wsm/screen/login/LoginViewModel.java
- app/src/test/java/com/framgia/wsm/screen/login/LoginPresenterTest.java
> Unit test login screen

- app/src/main/java/com/framgia/wsm/data/source/RequestRepository.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordModule.java
- app/src/main/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordPresenter.java
- app/src/test/java/com/framgia/wsm/screen/createnewpassword/CreateNewPasswordPresenterTest.java
Write Unit Test Create New Password
> [Unit Test] Write Unit Test Create New Password

- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
Remine https://dev.framgia.com/redmine/issues/133482
Update UI Manager Request
> ref task #133482 Update UI Manager Request

- app/src/main/java/com/framgia/wsm/data/model/Notification.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/main/MainContract.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewPagerAdapter.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationDialogFragment.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/TypeStatus.java
- build.gradle
- Ref bug#133159 Fix click item notifications to list request
- Effect : Screen list request manager, request personal
- https://dev.framgia.com/redmine/issues/133159
> ref bug#133159 Fix click item notifications to list request

- app/src/main/java/com/framgia/wsm/screen/notification/NotificationModule.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
Redmine https://dev.framgia.com/redmine/issues/133133
COMMON: Notification: Error message fails to display when tapping on "Change Group" Notification on list notification of popup
> ref bug #133133 Error message when click notification

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- Fix current month when pick dialog && Fix click item notifications to list request personal
- https://dev.framgia.com/redmine/issues/134553
- Sửa lại lúc chọn tháng cho đúng thời tháng hiện tại
- https://dev.framgia.com/redmine/issues/133159
- Sửa click item notifications khi click tới request cá nhân.
> ref bug#134553 Fix current month when pick dialog && Fix click item notifications to list request personal

- app/src/main/java/com/framgia/wsm/firebase/FireBaseMessageService.java
Fix click notification device
Effect screen: Request OT, Leave, Other, Manage OT, Leave, Other
> [Sprint Maintain]Fix click notification

- .gitignore
- app/build.gradle
- app/src/main/java/com/framgia/wsm/data/model/UserTimeSheet.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetModule.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/layout/fragment_time_sheet.xml
- build.gradle
- release_notes.txt
Update Time Sheet for compensation date
> Update Time Sheet for compensation date

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- ref bug#134533, bug#133159 Fix reload data when visible hint
- https://dev.framgia.com/redmine/issues/134553
- https://dev.framgia.com/redmine/issues/133159
- Reload lại dữ liệu khi đang ở màn hình đó
- Effect : List request personal, request manager
> ref bug#134533, bug#133159 Fix reload data when visible hint

- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetPresenter.java
- app/src/test/java/com/framgia/wsm/screen/timesheet/TimeSheetPresenterTest.java
Write unit test for time sheet screen
> [Unit test] Unit test for time sheet screen

- app/src/main/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarPresenter.java
- app/src/test/java/com/framgia/wsm/screen/holidaycalendar/HolidayCalendarPresenterTest.java
Unit test for holiday calendar
> [Unit tes] Unit test for holiday calendar

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/setting/SettingProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- https://dev.framgia.com/redmine/issues/134602
- Fix current group/branch with default setting
- Effect : Create/ Edit all type request screen
> ref bug#134602 Fix current group/branch with default setting

- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
Redmine https://dev.framgia.com/redmine/issues/134882
The current month displays incorrectly on search month field on list request screen
> ref bug #134882 Current month displays incorrectly

- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- https://dev.framgia.com/redmine/issues/134602
- Fix default group/branch when create form request
> ref_bug_134602 Fix default group/branch when create form request

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/fragment_member_request_detail.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
-Redmine https://dev.framgia.com/redmine/issues/134981
-add number hour in overtime request detail
> ref Support #134981 add number hour in overtime request detail

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsContract.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsFragment.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
> [Sprint maintain] Fix click notifications

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- Fix choose group when edit request others
- Effect : Edit request others
> [Sprint maintain] Fix choose branch when edit request others

- app/src/main/java/com/framgia/wsm/data/model/UserTimeSheet.java
- app/src/main/java/com/framgia/wsm/screen/timesheet/TimeSheetViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/wsm/widget/timesheet/TimeSheetView.java
- app/src/main/res/layout/fragment_time_sheet.xml
- Fix date compensation timesheet view
+ Tính số ngày làm bù trong tháng nếu có
+ Check null dữ liệu time sheet trả về
- Effect : TimeSheetView
> [Sprint maintain] Fix date compensation timesheet view

- app/src/main/java/com/framgia/wsm/data/model/Shifts.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/memberrequestdetail/MemberRequestDetailViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
Redmine https://dev.framgia.com/redmine/issues/135533
Total of overtime is incorrect when user creates OT request with time request is greater than 4 hours at the weekend and on Holiday
> Ref bug #135533  Total of overtime is incorrect

- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestAdapter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- https://dev.framgia.com/redmine/issues/132019
- Fix time request of LE (M)
- Effect : List request personal
> ref bug#132019 Fix time request of LE (M)

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestFragment.java
- app/src/main/res/layout/fragment_list_request.xml
- https://dev.framgia.com/redmine/issues/135687
- Fix hide floating button
> ref bug#135678 Fix hide floating button

- app/src/main/java/com/framgia/wsm/screen/statistics/StatisticsViewModel.java
- https://dev.framgia.com/redmine/issues/135872
- Fix reload data statistics when visible hint statistics screen
- Effect : Statistics screen
> ref bug#135872 Fix reload data statistics when visible hint

- app/src/main/java/com/framgia/wsm/screen/listrequest/ItemListRequestViewModel.java
Redmine https://dev.framgia.com/redmine/issues/133805
Fix Request time of IL(A) request displays incorrectly on Request list screen.
> ref bug #133805 Request time of IL(A) request displays incorrectly

- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestContract.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestPresenter.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewPagerAdapter.java
- https://dev.framgia.com/redmine/issues/136058
- Incorrectly when tapping on notifications
- Effect : List request personal
> ref bug#136058 Incorrectly when tapping  on notifications

- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- Update app when notifications inform update
> [Sprint maintain] Update app when have notifications inform update

- app/src/main/java/com/framgia/wsm/firebase/FireBaseMessageService.java
- https://dev.framgia.com/redmine/issues/136544
- Fix update version (  Hiện tại firebase trả data về theo kiểu type nên check lại loại type để truyền dữ liệu cho đúng )
> [Sprint maintain] Fix update version

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/common/DateTimeUtils.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManager.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
Redmine https://dev.framgia.com/redmine/issues/136339
Edit request: Date time should be display date of time request instead of current day when tapping on time request on edit request screen
> ref support #136339 Date time should be display date of time request

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
Redmine https://dev.framgia.com/redmine/issues/136563
Error message displays when choosing valid search time
> ref bug #136563 Error message displays when choosing valid search time

- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/layout/activity_confirm_overtime.xml
- app/src/main/res/layout/activity_confirm_request_leave.xml
- app/src/main/res/layout/activity_confirm_request_off.xml
- app/src/main/res/menu/menu_drawer.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
- dependencies.gradle
- https://dev.framgia.com/redmine/issues/136787
- Update version firebase and Fix title all type request from text "leave" to "day off
> [Sprint maintain] Update version firebase and Fix title all type request

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/wsm/data/event/InternetEvent.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/NetworkModule.java
- app/src/main/java/com/framgia/wsm/data/source/remote/api/middleware/InterceptorImpl.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/main/MainActivity.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/utils/Constant.java
- app/src/main/java/com/framgia/wsm/utils/InternetManager.java
- app/src/main/java/com/framgia/wsm/utils/navigator/Navigator.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/137368
- Check internet connection
> [Sprint maintain] Check internet connection

- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- https://dev.framgia.com/redmine/issues/136339
- Fix incorrect date when edit birthday 
- Effect : Update profile
> ref bug#136339 Fix incorrect date when edit birthday

- app/src/main/java/com/framgia/wsm/screen/EndlessRecyclerOnScrollListener.java
- app/src/main/java/com/framgia/wsm/screen/listrequest/ListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/java/com/framgia/wsm/screen/notification/NotificationViewModel.java
- https://dev.framgia.com/redmine/issues/138030
- Fix load more recycleview
> [Sprint Maintain] Fix load more recycleview

- app/src/main/java/com/framgia/wsm/screen/confirmrequestoff/ConfirmRequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/confirmovertime/ConfirmOvertimeViewModel.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
- dependencies.gradle
- Fix minor bugs and check internet connection
https://dev.framgia.com/redmine/issues/136339
https://dev.framgia.com/redmine/issues/136787
https://dev.framgia.com/redmine/issues/137368
> Release 1.0.2

- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/drawable/border_button_red.xml
- app/src/main/res/drawable/border_textview_stroke_green.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/layout_working_other.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/140010
- information user ui #2
> [Sprint maintain] Information User Ui #2

- app/src/main/java/com/framgia/wsm/data/model/User.java
- app/src/main/java/com/framgia/wsm/data/model/VehicleInfo.java
- app/src/main/java/com/framgia/wsm/screen/profile/ProfileViewModel.java
- app/src/main/java/com/framgia/wsm/utils/binding/BindingUtils.java
- app/src/main/res/drawable-xxhdpi/ic_account_id.xml
- app/src/main/res/drawable-xxhdpi/ic_bank_info.xml
- app/src/main/res/drawable-xxhdpi/ic_current_address.xml
- app/src/main/res/drawable-xxhdpi/ic_distance_from_office.xml
- app/src/main/res/drawable-xxhdpi/ic_home_phone.xml
- app/src/main/res/drawable-xxhdpi/ic_identity.xml
- app/src/main/res/drawable-xxhdpi/ic_license_plate.xml
- app/src/main/res/drawable-xxhdpi/ic_marital_status.xml
- app/src/main/res/drawable-xxhdpi/ic_number_of_child.xml
- app/src/main/res/drawable-xxhdpi/ic_permanent_address.xml
- app/src/main/res/drawable-xxhdpi/ic_personal_email.xml
- app/src/main/res/drawable-xxhdpi/ic_place_of_birth.xml
- app/src/main/res/drawable-xxhdpi/ic_vehicle.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/layout_working_other.xml
- https://dev.framgia.com/redmine/issues/140246
- Information User logic #2
> [Sprint maintain] Information User logic #2

- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileAdapter.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileModule.java
- app/src/main/java/com/framgia/wsm/screen/updateprofile/UpdateProfileViewModel.java
- app/src/main/res/drawable/border_textview_update.xml
- app/src/main/res/layout/activity_update_profile.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/140348
- Mainpage update information
> [Sprint maintain] Mainpage update information

- build.gradle
- circle.yml
- dependencies.gradle
Support: 
- https://dev.framgia.com/redmine/issues/136538
Task:
- https://dev.framgia.com/redmine/issues/140010
- https://dev.framgia.com/redmine/issues/140499
Fix:
- https://dev.framgia.com/redmine/issues/138030
> Release 1.1

- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ItemManageListRequestViewModel.java
- app/src/main/java/com/framgia/wsm/screen/managelistrequests/ManageListRequestsViewModel.java
- app/src/main/res/layout/fragment_manage_list_requests.xml
- app/src/main/res/layout/fragment_time_sheet.xml
- Remove checkbox with status rejected
- https://dev.framgia.com/redmine/issues/142248
> Remove checkbox with status rejected

- app/src/main/java/com/framgia/wsm/screen/requestleave/RequestLeaveActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffActivity.java
- app/src/main/java/com/framgia/wsm/screen/requestoff/RequestOffViewModel.java
- app/src/main/java/com/framgia/wsm/screen/requestovertime/RequestOvertimeActivity.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManager.java
- app/src/main/java/com/framgia/wsm/widget/dialog/DialogManagerImpl.java
- app/src/main/res/layout/activity_request_off.xml
- app/src/main/res/layout/fragment_time_sheet.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> [Sprint Maintain] Feature fix ui dialog error leave request
